using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using UnityEngine.SceneManagement;


namespace UnityEngine.XR.ARFoundation
{
    public class Tutorial_pictureGame : MonoBehaviour
    {
        //Material[] mat = new Material[2];
        //Material[] rgb_mat = new Material[3];
        public bool flag_scan_mode;
        bool flag_game_mode;
        bool is_check_pos_true;
        bool pet_move_flag;
        bool do_nothing;
        bool m_bPause;
        bool check_pos_clicked;
        bool go_to_below;
        int cnt_founded;
        Petctrl petctrl_script;
        vid_control vid_ctrl_script;
        //public GameObject scanning_panel;
        public GameObject gamming_panel;
        public GameObject video_screen;
        public GameObject take_picture_bt;
        public GameObject shoot_bt;
        public GameObject gamming_take_picture_bt;
        public GameObject gamming_shoot_bt;
        public GameObject guide_circle_orange;
        public GameObject start_game_bt;
        public GameObject start_game_bt_no;
        public GameObject Arrow_L;
        public GameObject Arrow_R;
        //public Image guide_image;
        public List<Sprite> guide_img_set = new List<Sprite>();
        public bool flag_game_started;


        ARMeshManager Meshing;
        //MeshRenderer occ_mat;
        //MeshRenderer white_mat;
        //MeshRenderer red_mat;
        //MeshRenderer green_mat;
        //MeshRenderer blue_mat;

        //MeshFilter occ_prefab;
        //MeshFilter white_prefab;
        List<Vector3> extracted_points = new List<Vector3>();
        List<Vector3> list_points = new List<Vector3>();
        List<GameObject> Gb_points = new List<GameObject>();
        Vector3 touched_mesh_pose;
        //Vector3 oldPosition; //ì†ë„ ê³„ì‚° ìœ„í•œ ì´ì „ í”„ë ˆì„ í¬ì¸íŠ¸ ì €ì¥

        float time_remaining;
        public float min_y = 0;
        public Image timer_radial_image;
        public Image gamming_timer_radial_image;
        public TMP_Text Panel_text;
        public GameObject item_meal;
        public TMP_Text time_text;
        public TMP_Text item_text;

        Vector2 Center_device;
        Vector2 touch_pos;
        RaycastHit hit;
        private Animator anim;
        private bool track_flag;

        int local_success = 0;
        int global_success = 0;
        int game_local_success = 0;
        int game_global_success = 0;

        int cnt_next_bt_clicked;
        public GameObject tutorial_panel;
        public GameObject tutorial_bt;
        public TMP_Text tutorial_msg;

        // Start is called before the first frame update
        void Start()
        {
            Center_device = new Vector2(Screen.width / 2f, Screen.height / 2f);
            petctrl_script = GameObject.Find("Main Camera").GetComponent<Petctrl>();
            vid_ctrl_script = GameObject.Find("Scripts").GetComponent<vid_control>();
            //scanning_panel.SetActive(false);
            gamming_panel.SetActive(false);
            start_game_bt.SetActive(false);
            start_game_bt_no.SetActive(false);
            Arrow_L.SetActive(false);
            Arrow_R.SetActive(false);
            //Meshing = GameObject.Find("Meshing").GetComponent<ARMeshManager>();
            //occ_prefab = GameObject.Find("OcclusionMeshPrefab").GetComponent<MeshFilter>();
            //white_prefab = GameObject.Find("white_mesh_prefab").GetComponent<MeshFilter>();
            //occ_mat = GameObject.Find("OcclusionMeshPrefab").GetComponent<MeshRenderer>();
            //white_mat = GameObject.Find("white_mesh_prefab").GetComponent<MeshRenderer>();
            //red_mat = GameObject.Find("red_mesh_prefab").GetComponent<MeshRenderer>();
            //green_mat = GameObject.Find("green_mesh_prefab").GetComponent<MeshRenderer>();
            //blue_mat = GameObject.Find("blue_mesh_prefab").GetComponent<MeshRenderer>();
            //mat[0] = occ_mat.material;
            //mat[1] = white_mat.material;
            //rgb_mat[0] = red_mat.material;
            //rgb_mat[1] = green_mat.material;
            //rgb_mat[2] = blue_mat.material;
            touched_mesh_pose = Vector3.zero;
            cnt_founded = 0;
            //oldPosition = Vector3.zero;
            time_text.enabled = false;

            cnt_next_bt_clicked = 0;
        }

        // Update is called once per frame
        void Update()
        {
            if(petctrl_script.blink_circle.activeSelf == true)
            {
                var ray_blink = Camera.main.ScreenPointToRay(Center_device);
                Physics.Raycast(ray_blink, out var hit_blink, float.PositiveInfinity);

                if (hit_blink.transform.name.StartsWith("Mesh"))
                    petctrl_script.blink_circle.transform.position = hit_blink.point;
            }
            

            if (flag_scan_mode)
            {
                scan_mode();
            }

            if (flag_game_mode)
            {
                gaming_mode();

            }
        }

        public void picture_next_bt_clicked()
        {
            Debug.Log("cnt_next_bt_clicked: " + cnt_next_bt_clicked);
            if (cnt_next_bt_clicked == 0)
            {
                tutorial_bt.SetActive(false);
                tutorial_msg.text = "ë™ì˜ìƒì„ ë³´ê³  ë°©ì„ ë‘˜ëŸ¬ë³´ëŠ” ë°©ë²•ì„ ë°°ì›Œë³¼ê¹Œìš”?";
                vid_ctrl_script.excute_vid();
                cnt_next_bt_clicked++;
            }

            else if (cnt_next_bt_clicked == 1)
            {
                tutorial_msg.text = "ê°•ì•„ì§€ì™€ í•¨ê»˜ ë°© ì•ˆì„ êµ¬ê²½í•´ë³¼ê¹Œìš”?";
                cnt_next_bt_clicked++;
                start_scan();
            }

            else if (cnt_next_bt_clicked == 2)
            {
                tutorial_msg.text = "ì´ì œ ê°•ì•„ì§€ë¥¼ ë¶ˆëŸ¬ì˜¬ ìˆ˜ ìˆì–´ìš”. í•œë²ˆ ë¶ˆëŸ¬ì™€ ë³¼ê¹Œìš”?";
                flag_scan_mode = false;
                guide_circle_orange.SetActive(false);
                petctrl_script.Load_pet_bt.SetActive(true);
                petctrl_script.blink_circle.SetActive(true);
                Arrow_L.SetActive(false);
                Arrow_R.SetActive(false);
                time_text.text = "";

                cnt_next_bt_clicked++;
            }

            else if (cnt_next_bt_clicked == 3)
            {
                tutorial_msg.text = "ê°•ì•„ì§€ë¥¼ ë¶ˆëŸ¬ì™”ì–´ìš”!";
                petctrl_script.blink_circle.SetActive(false);
                petctrl_script.SetPosition();

                var Load_pet_bt = GameObject.Find("Load_pet");
                Load_pet_bt.SetActive(false);
                Invoke("picture_next_bt_clicked", 5f);
                time_text.text = "";

                cnt_next_bt_clicked++;
            }

            else if (cnt_next_bt_clicked == 4)
            {
                tutorial_msg.text = "ê°•ì•„ì§€ë¥¼ ë”°ë¼ ì´ë™í•´ë³¼ê¹Œìš”?";
                Invoke("picture_next_bt_clicked", 7f);
                start_game();
                cnt_next_bt_clicked++;
            }

            else if (cnt_next_bt_clicked == 5)
            {
                tutorial_msg.text = "ê°•ì•„ì§€ê°€ ë³´ì´ë„ë¡ ì‚¬ì§„ì„ ì°ì–´ë³¼ê¹Œìš”?";
                tutorial_bt.SetActive(true);
                cnt_next_bt_clicked++;
            }

            else if (cnt_next_bt_clicked == 6)
            {
                tutorial_bt.SetActive(false);
                tutorial_msg.text = "ì¤€ë¹„ê°€ ë˜ë©´ ìë™ìœ¼ë¡œ ì‚¬ì§„ì´ ì°í˜€ìš”!";
                Invoke("check_pos", 5f);
                //Invoke("picture_next_bt_clicked", 10f);
                cnt_next_bt_clicked++;
                Debug.Log("check1");
            }

            else if (cnt_next_bt_clicked == 7)
            {
                tutorial_bt.SetActive(true);
                tutorial_msg.text = "ë‹¤ì‹œ í•œ ë²ˆ ê°•ì•„ì§€ë¥¼ ë”°ë¼ê°€ ë³¼ê¹Œìš”?";
                cnt_next_bt_clicked++;
                Debug.Log("check2");
            }

            else if (cnt_next_bt_clicked == 8)
            {
                tutorial_bt.SetActive(false);
                tutorial_msg.text = "ì¤€ë¹„ê°€ ë˜ë©´ ìë™ìœ¼ë¡œ ì‚¬ì§„ì´ ì°í˜€ìš”!";
                Invoke("check_pos", 5f);
                //Invoke("picture_next_bt_clicked", 10f);
                cnt_next_bt_clicked++;
                Debug.Log("check3");
            }

            else if (cnt_next_bt_clicked == 9)
            {
                tutorial_msg.text = "ì˜ í•˜ì…¨ì–´ìš”! ê°•ì•„ì§€ì™€ ì¡°ê¸ˆ ë” ì¹œí•´ì§„ ê²ƒ ê°™ì§€ ì•Šë‚˜ìš”?";
                //check_pos();
                Invoke("load_tutorial_page", 9f);
                cnt_next_bt_clicked = 0;
                flag_game_mode = false;
            }


        }

        void load_tutorial_page ()
        {
            SceneManager.LoadScene("Tutorial");
        }

        public void print_trackable()
        {
            GameObject trackables = GameObject.Find("Trackables");
            var childs = trackables.transform.childCount;

            for (int i = 0; i < childs; i++)
            {
                var childs_name = trackables.transform.GetChild(i).transform.name;
                Debug.Log(childs_name);
            }
        }

        public void scan_mode()
        {
            ////Meshing.meshPrefab = white_prefab; ìŠ¤ìºë‹ íš¨ê³¼ë¥¼ ì–´ë–»ê²Œ ì¤„ì§€??
            ////ìŠ¤ìºë‹ì´ ì™„ë£Œë˜ë©´ ì¢…ë£Œ ë²„íŠ¼ì„ ëˆŒëŸ¬ì£¼ì„¸ìš” í´ë¦­-> ì¢…ë£Œë²„íŠ¼ì„ ìƒì„±í•´ì£¼, ìŠ¤ìºë‹ì´ ì™„ë£Œë˜ë©´ ìŠ¤ìºë‹ì„ ì¢…ë£Œí•˜ê³  ë§ˆì»¤ë¥¼ ë‚¨ê²¨ ë†“ëŠ”ë‹¤  
            ////ìŠ¤ìºë‹ í•˜ë©´ì„œ ë§ˆì»¤ë¥¼ ë‚¨ê²¨ë†“ëŠ” ë°©ì‹ í˜¹ì€ ìë™ìœ¼ë¡œ ìŠ¤ìºë‹ í¬ì¸íŠ¸ë“¤ì„ ìƒì„±í•´ì¤€ë‹¤
            ////scanningì´ ì™„ë£Œë˜ë©´, ë°”ë‹¥ì— markerê°€ í‘œì‹œë˜ê²Œ í•  ìˆ˜ ìˆë‚˜?  
            //var Center_device = new Vector2(Screen.width / 2f, Screen.height / 2f);
            //var ray = Camera.main.ScreenPointToRay(Center_device);
            //var hasHit = Physics.Raycast(ray, out var hit, float.PositiveInfinity);
            //if(hasHit)
            //{
            //    //pointë“¤ì„ ì €ì¥í•œë‹¤.
            //    //var origin = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            //    //origin.transform.localScale = Vector3.one * 0.05f;
            //    //origin.transform.position = hit.point;
            //    list_points.Add(hit.point);
            //    //Debug.Log("length of list_points: " + list_points.Count);

            //}
            ////modeê°€ ëë‚  ë•ŒëŠ” list_pointsë¡œë¶€í„° 7ê°œì˜ pointë“¤ì„ ê³ ë¥¸ë‹¤.


            //ë§Œì•½ ì‹œê°„ë‚´ì— take picture ë²„íŠ¼ì„ ëˆ„ë¥¸ë‹¤ë©´ local sucess += 1
            //local successê°€ 3ë²ˆ ì´ìƒì´ë©´ global_sucess += 1
            //global successëŠ” ì´¬ì˜í•œ ë¬¼ì²´ì˜ ê°¯ìˆ˜ë¡œ ìƒê°í•˜ë©´ ëœë‹¤.

            if (time_remaining < 0)
            {
                flag_scan_mode = false;
                guide_circle_orange.SetActive(false);
                petctrl_script.Load_pet_bt.SetActive(true);
                petctrl_script.blink_circle.SetActive(true);

                //Meshing.enabled = false;
                //petctrl_script.SetPosition();
                Arrow_L.SetActive(false);
                Arrow_R.SetActive(false);
                time_text.text = "";
                picture_next_bt_clicked();
                return;
            }
            time_remaining -= Time.deltaTime;
            time_text.text = ((int)time_remaining % 60).ToString() +
                             "ì´ˆ í›„ì— ê²Œì„ì´ ì‹œì‘ë©ë‹ˆë‹¤." +
                             "\nê°•ì•„ì§€ì—ê²Œ ë°©ì„ êµ¬ê²½ì‹œì¼œ ì£¼ì„¸ìš”!" +
                             "\n\n\n\n\n\n\n\n\n\nê°•ì•„ì§€ê°€ ë‘˜ëŸ¬ë³¼ ìˆ˜ ìˆë„ë¡ í™”ë©´ì„ ì¢Œìš°ë¡œ ì›€ì§ì—¬ ë³¼ê¹Œìš”?";
            var ray = Camera.main.ScreenPointToRay(Center_device);
            var hasHit = Physics.Raycast(ray, out hit, float.PositiveInfinity);
            //var currentPoisition = hit.point;
            //var dis = (currentPoisition - oldPosition);
            //var distance = Mathf.Sqrt(Mathf.Pow(dis.x, 2) + Mathf.Pow(dis.y, 2) + Mathf.Pow(dis.z, 2));
            //var velocity = distance / Time.deltaTime;
            //oldPosition = currentPoisition;
            //Debug.Log("velocity: " + velocity);


            if (hasHit && hit.transform.name.StartsWith("Mesh"))//
            {
                if (min_y > hit.point.y) min_y = hit.point.y;
                if (time_remaining < 10)
                {
                    var diff = Mathf.Abs((hit.point.y - min_y) / min_y);
                    //Debug.Log(hit.transform.name + "\tdiff: " + diff
                    //          + "\thit.point.y: " + hit.point.y
                    //          + "\tmin_y: " + min_y);

                    if (diff < 0.05)
                    {
                        list_points.Add(hit.point);
                    }
                }
                guide_circle_orange.transform.position = hit.point + Vector3.up * 0.1f;
                guide_circle_orange.transform.eulerAngles = new Vector3(0f, Camera.main.transform.eulerAngles.y, 0f);
                //MeshRenderer prefab_mat = hit.transform.GetComponent<MeshRenderer>();
                //Debug.Log(prefab_mat.material);
                //MeshFilter collider_mat = hit.transform.GetComponent<MeshFilter>();
                //MeshRenderer renderer_mat = collider_mat.GetComponent<MeshRenderer>();
                //Debug.Log(collider_mat + "\t" + collider_mat.name + "\t" + collider_mat.GetInstanceID() + "\t"
                //        + collider_mat.mesh);
            }

            //if (time_remaining > 0)
            //{
            //    //Debug.Log("Scanning mode ì‹¤í–‰ì¤‘");
            //    time_remaining -= Time.deltaTime;
            //    timer_radial_image.fillAmount = time_remaining / 10f;
            //}
            //else
            //{
            //    //take picture ë²„íŠ¼ì„ ëˆ„ë¥¸ í›„ 10ì´ˆê°€ ê²½ê³¼í•˜ë©´ ë‹¤ì‹œ shoot_btë¥¼ êº¼ì£¼ê³  take_picture btì„ ì¼œì¤€ë‹¤
            //    take_picture_bt.SetActive(true);
            //    shoot_bt.SetActive(false);
            //    timer_radial_image.fillAmount = 1f;
            //}


        }

        public void Pause()
        {
            if (m_bPause == false)
            {
                m_bPause = true;
            }
            else
            {
                m_bPause = false;
            }
        }

        void extract_points()
        {
            int len_points = list_points.Count;
            Debug.Log("len of list_points: " + len_points);
            for (int i = 0; i < 10; i++)
            {
                int index_point = (len_points / 9) * i;
                if (index_point == list_points.Count) index_point -= 1;
                extracted_points.Add(list_points[index_point]);//ì‹¤ì œ ì‚¬ìš©ì€ 1ë¶€í„° 8ê¹Œì§€
                Debug.Log("index: " + i.ToString() + "\t     point:" +
                           extracted_points[i].x + ",\t" + extracted_points[i].y + ",\t" + extracted_points[i].z);
                //var origin = GameObject.CreatePrimitive(PrimitiveType.Cube);
                //origin.transform.localScale = Vector3.one * 0.2f;
                //origin.transform.position = list_points[index_point];
                //Gb_points.Add(origin);

            }
            System.Range range = 0..5;
            var shuffled_idx = MakeRandomNumbers(9)[range];

            for (int i = 0; i < shuffled_idx.Length; i++)
            {
                var item_created = Instantiate(item_meal, extracted_points[shuffled_idx[i]] + 0.1f * Vector3.up, hit.transform.rotation);
                var gb_name = "item_" + shuffled_idx[i].ToString();
                Debug.Log(gb_name);
                item_created.transform.name = gb_name;
                Gb_points.Add(item_created);
            }
            //list_points.Clear();
            extracted_points.Clear();

        }

        public void gaming_mode()
        {
            /*
            Vector3 cur_target_pos = extracted_points[cnt_founded];
            Vector3 next_target_pos = extracted_points[cnt_founded + 1];

            if (Input.touchCount > 0)//í«ì´ í™”ë©´ì— ì¡´ì¬í•  ê²½ìš°, í™”ë©´ì„ í„°ì¹˜í•˜ë©´ ê·¸ê³³ìœ¼ë¡œ ì´ë™ì‹œì¼œì¤€ë‹¤. ê·¸ëŸ¬ê¸° ìœ„í•´ ì´ë™í•  ëª©í‘œ ìœ„ì¹˜ë¥¼ ì—…ë°ì´íŠ¸ ì‹œì¼œì¤€ë‹¤. 
            {
                Debug.Log("Pet is in the Scene, screen touched");
                Touch touch2 = Input.GetTouch(0);
                if (Input.GetTouch(0).phase == TouchPhase.Ended)
                {
                    track_flag_changed = true;
                    MeshRenderer render = Gb_points[cnt_founded + 1].GetComponent<MeshRenderer>();
                    render.material = rgb_mat[0];//change to red
                    petctrl_script.track_flag = true;
                    var ray = Camera.main.ScreenPointToRay(touch2.position);
                    var hasHit = Physics.Raycast(ray, out var hit, float.PositiveInfinity);
                    Debug.Log("tracking point ì €ì¥: " + hit.point);
                    if (hasHit) touched_mesh_pose = hit.point;
                }
            }

            if (touched_mesh_pose != Vector3.zero) //Vector3.zeroëŠ” ì´ˆê¸°ê°’.
            {
                petctrl_script.move_to_point(touched_mesh_pose);
            }

            Debug.Log(petctrl_script.track_flag + "\t" + track_flag_changed);


            //track_flagê°€ falseê°€ ë˜ì—ˆì„ ë•Œ í•œë²ˆë§Œ ì‹¤í–‰ì‹œí‚¤ëŠ” ì‘ì—…ì„ í•´ì£¼ëŠ” í•¨ìˆ˜ê°€ í•˜ë‚˜ í•„ìš”í•˜ë‹¤
            //track_flagê°€ falseê°€ ë˜ì—ˆë‹¤ëŠ” ê²ƒì€ objectê°€ ì†ìœ¼ë¡œ ì°ì€ ì§€ì ê³¼ ë¹„ìŠ·í•œ ê³³ì— ìˆë‹¤ëŠ” ì´ì•¼ê¸°ì´ë‹¤.
            if (petctrl_script.track_flag == false && track_flag_changed)
            {
                //í„°ì¹˜í•œ ê³³ìœ¼ë¡œ í«ì´ ì´ë™í–ˆì„ ë•Œ, í•´ë‹¹ ìœ„ì¹˜ì™€ next_target_poseìœ„ì¹˜ê°€ ì˜¤ì°¨ë²”ìœ„ ì´ë‚´ì— ìˆëŠ”ì§€ í™•ì¸í•´ì•¼ í•œë‹¤. 
                track_flag_changed = false;
                Debug.Log("Petê³¼ target pos ì‚¬ì´ì˜ ê±°ë¦¬: " +
                           Vector3.Distance(petctrl_script.spawnedObject.transform.position, Gb_points[cnt_founded + 1].transform.position));
                if (Vector3.Distance(petctrl_script.spawnedObject.transform.position, Gb_points[cnt_founded + 1].transform.position) < 0.2f)
                {
                    //petì´ target object ê·¼ì²˜ë¡œ ì´ë™í–ˆìœ¼ë¯€ë¡œ Target objectì˜ ìƒ‰ì„ ì´ˆë¡ìœ¼ë¡œ ë°”ê¿”ì¤€ í›„ cnt_foundedë¥¼ ì˜¬ë ¤ì¤€ë‹¤
                    Debug.Log("ìƒ‰ìƒì„ ì´ˆë¡ìœ¼ë¡œ ë°”ê¿” ì¤ë‹ˆë‹¤. í˜„ì¬ ì°¾ì€ ê°œìˆ˜: " + (cnt_founded + 1).ToString());
                    MeshRenderer render = Gb_points[cnt_founded + 1].GetComponent<MeshRenderer>();
                    render.material = rgb_mat[1];// change to green
                    cnt_founded += 1;
                }
                else
                {
                    //petì˜ ìœ„ì¹˜ê°€ target posì™€ ë” ê°€ê¹Œì›Œì ¸ì•¼ í•˜ë¯€ë¡œ ë‹¤ì‹œ íŠ¸ë ˆí‚¹ ëª¨ë“œë¡œ ì „í™˜ì‹œì¼œì¤˜ì•¼í•œë‹¤.
                    petctrl_script.track_flag = true;
                    Debug.Log("ë¬¼ì²´ë¥¼ ì°¾ì•„ê°€ì£¼ì„¸ìš”");
                }
            }
            */

            petctrl_script.spawnedObject.transform.eulerAngles = new Vector3(0f, petctrl_script.spawnedObject.transform.eulerAngles.y, 0f);
            petctrl_script.spawnedObject.transform.GetChild(0).transform.eulerAngles = new Vector3(0f, petctrl_script.spawnedObject.transform.GetChild(0).transform.eulerAngles.y, 0f);
            if (petctrl_script.spawnedObject.transform.GetChild(0).transform.position.y < -5f)
            {
                petctrl_script.spawnedObject.transform.GetChild(0).transform.position =
                    new Vector3(petctrl_script.spawnedObject.transform.GetChild(0).transform.position.x,
                                0, petctrl_script.spawnedObject.transform.GetChild(0).transform.position.z);
            }

            //Debug.Log("Pome Angle: " + petctrl_script.spawnedObject.transform.eulerAngles
            //        + "\tPome_inva Angle: " + petctrl_script.spawnedObject.transform.GetChild(0).transform.eulerAngles
            //        +"\tPome_position: " + petctrl_script.spawnedObject.transform.position
            //        + "\tPome_inva_position: " + petctrl_script.spawnedObject.transform.GetChild(0).transform.position);

            if (do_nothing) return;
            if (pet_move_flag)
            {
                //BoxCollider collider = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<BoxCollider>();
                //Rigidbody rg_body = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Rigidbody>();
                //rg_body.useGravity = true;
                //collider.isTrigger = true;

                track_flag = true;
                anim = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Animator>();
                anim.Play("Walk");
                //Debug.Log("pet is moving");
                touched_mesh_pose = Gb_points[game_global_success].transform.position;
                pet_move_flag = false;
            }

            if (touched_mesh_pose != Vector3.zero) move_to_point(touched_mesh_pose); //Vector3.zeroëŠ” ì´ˆê¸°ê°’. 
            if (track_flag) return;
            else
            {
                anim = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Animator>();
                anim.Play("Idle");
            }

            //if (!go_to_below) return;

            //if (time_remaining > 0)
            if(time_remaining > 0)
            {
                time_remaining -= Time.deltaTime;
            }
            //gamming_timer_radial_image.fillAmount = time_remaining / 10f;

            //check_pos(); //ì˜¬ë°”ë¥¸ í¬ì¦ˆë¡œ ì´¬ì˜í–ˆëŠ”ì§€ í™•ì¸í•´ì£¼ëŠ” í•¨ìˆ˜
            if (!check_pos_clicked) return;
            check_pos_clicked = false;
            //else //ì‹œê°„ì´ ë‹¤ ê²½ê³¼í–ˆì„ ê²½ìš°.
                 //CASE1: ì‹¤ì œ ì‹œê°„ì´ ë‹¤ ê²½ê³¼ë˜ì–´ì„œ ë„˜ì–´ì˜¨ ê²½ìš°.(is_check_pos_true==false)
                 //CASE2: check_posí•¨ìˆ˜ì— ì˜í•´ ë„˜ì–´ì˜¨ ê²½ìš°.(is_check_pos_true==true, ì •ë‹µì¼ ì‹œ check_posì—ì„œ time_remainingì„ ê°•ì œë¡œ 0ìœ¼ë¡œ ë§Œ)
            
            if (is_check_pos_true)//ì‚¬ì§„ ì°ê¸° ì„±ê³µí•œ ê²½ìš°
            {
                Debug.Log("game_mode_picture bt clicked ì‹¤í–‰");
                Invoke("picture_next_bt_clicked", 7f);
                is_check_pos_true = false;
                //if (game_local_success < 2)
                //{

                //}
                //else
                {
                    //ë­”ê°€ ë¦¬ì•¡ì…˜ ê´€ë ¨ëœ í•¨ìˆ˜ë‚˜ ì• ë‹ˆë©”ì´ì…˜, í˜¹ì€ ë³´ìƒì£¼ê¸°
                    //global success ë¥¼ 1ì˜¬ë ¤ì£¼ëŠ” íƒ€ì´ë°ì— Pet_move_flagë„ Trueë¡œ ë°”ê¿”ì¤€ë‹¤.

                    petctrl_script.set_text_speechBubble("ì‚¬ì§„ì„ ì°ì—ˆì–´ìš”!");
                    Gb_points[game_global_success].SetActive(false); //global succesê°€ 0ì´ ë˜ë©´ Gb_pointsë„ clear í•´ì¤€ë‹¤.
                    game_global_success += 1;
                    if (game_global_success == 5) Gb_points.Clear();
                    //guide_image.sprite = guide_img_set[0]; //reset ì´ë¯¸ì§€ë¡œ
                    anim = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Animator>();
                    var rand_idx = MakeRandomNumbers(4)[0];
                    if (rand_idx == 0)
                    {
                        anim.Play("277_Skill_Dance");
                    }
                    else if (rand_idx == 1)
                    {
                        anim.Play("067_Idle_Blend_LieOnBack");
                    }
                    else if (rand_idx == 2)
                    {
                        anim.Play("302_Stroll");
                    }
                    else if (rand_idx == 3)
                    {
                        anim.Play("226_Play_Left_Spin");
                    }
                    do_nothing = true;
                    //float loop_escape_time = 100.0f;
                    //while(true)
                    //{
                    //    loop_escape_time -= Time.deltaTime;
                    //    Debug.Log(loop_escape_time);
                    //    if (loop_escape_time < 0) break;
                    //}
                    Invoke("set_pet_move_flag_true", 7f);// 5ì´ˆ í›„ ë‹¤ìŒ Targetìœ¼ë¡œ ì´ë™
                    item_text.text = "ì°¾ì€ ê°œìˆ˜: " + game_global_success.ToString() + "ê°œ";
                }
            }
            //else //ì‚¬ì§„ ì°ê¸° ì‹¤íŒ¨í•œ ê²½ìš°
            //{
            //    time_remaining = 10.0f;
            //}


            //gamming_take_picture_bt.SetActive(true);
            //gamming_shoot_bt.SetActive(false);
            //if(time_remaining < 0)
                
                //gamming_timer_radial_image.fillAmount = 1f;
            //time_remaining = 10.0f;
                
            

            //if (EventSystems.EventSystem.current.IsPointerOverGameObject(Input.GetTouch(0).fingerId))
            //    return;

            //if (Input.touchCount > 0)//í«ì´ í™”ë©´ì— ì¡´ì¬í•  ê²½ìš°, ê²Œì„ ì˜¤ë¸Œì íŠ¸ë¥¼ í„°ì¹˜í•˜ë©´ ê·¸ê³³ìœ¼ë¡œ ì´ë™ì‹œì¼œì¤€ë‹¤.  
            //{
            //    //Debug.Log("Pet is in the Scene, screen touched");
            //    touch_pos = InputSystem.Pointer.current.position.ReadValue();
            //    if (touch_pos.y / Screen.height > 0.15f)
            //    {
            //        var ray1 = Camera.main.ScreenPointToRay(touch_pos);
            //        var hasHit1 = Physics.Raycast(ray1, out var hit1, float.PositiveInfinity);
            //        if (hasHit1 && hit1.transform.name.StartsWith("item"))//itemì„ í´ë¦­ í•  ë•Œë§Œ ì›€ì§ì´ê¸°
            //        {
            //            track_flag = true;
            //            anim = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Animator>();
            //            anim.Play("Walk");
            //            Debug.Log("item is touched___gameMode");
            //            touched_mesh_pose = hit1.point;
            //        }
            //    }
            //}

        }

        private void set_pet_move_flag_true()
        {
            do_nothing = false;
            if (game_global_success < 5)
            {
                set_to_kinematic();
                pet_move_flag = true;
            }
            //else
            //{
            //    Debug.Log("ê²Œì„ ì¢…ë£Œ!");
            //    set_to_gravity();
            //    game_global_success = 0;
            //    game_local_success = 0;
            //    anim = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Animator>();
            //    anim.Play("Idle");
            //    flag_game_started = false;
            //    flag_game_mode = false;
            //    gamming_panel.SetActive(false);
            //    time_text.text = "ê²Œì„ì„ ë‹¤ì‹œ í•œ ë²ˆ í•´ë³¼ê¹Œìš”?";
            //    start_game_bt_no.SetActive(true);
            //    start_game_bt.SetActive(true);
            //}
        }

        public void check_pos()
        {


            //if (time_remaining < 7) //í˜„ì¬ëŠ” 7ì´ˆ ë°‘ìœ¼ë¡œ ë–¨ì–´ì§€ê¸°ë§Œ í•˜ë©´ ì„±ê³µìœ¼ë¡œ ì·¨ê¸‰
            
            AudioSource audio = GameObject.Find("Audio player_cam").GetComponent<AudioSource>();
            audio.Play();
            Debug.Log("ì‚¬ì§„ ì°ê¸° ì„±ê³µ!");
            is_check_pos_true = true;
            time_remaining = 0;
            

            check_pos_clicked = true;
            return;
        }

        public void move_to_point(Vector3 hitpoint)
        {
            if (track_flag)
            {

                //if (Vector3.Distance(petctrl_script.spawnedObject.transform.position, hitpoint) > 0.1f)
                //{
                //    petctrl_script.spawnedObject.transform.position = Vector3.MoveTowards(petctrl_script.spawnedObject.transform.position, hitpoint, 0.01f);
                //    Vector3 dir = hitpoint - petctrl_script.spawnedObject.transform.position;
                //    dir.y = 0f;
                //    Quaternion rot = Quaternion.LookRotation(dir.normalized);
                //    petctrl_script.spawnedObject.transform.rotation = rot;
                //}
                //Debug.Log("track_flag is true, check the distance: " + Vector2.Distance(new Vector2(petctrl_script.spawnedObject.transform.position.x, petctrl_script.spawnedObject.transform.position.z),
                //                     new Vector2(hitpoint.x, hitpoint.z)));
                if (Vector2.Distance(new Vector2(petctrl_script.spawnedObject.transform.position.x, petctrl_script.spawnedObject.transform.position.z),
                                     new Vector2(hitpoint.x, hitpoint.z)) > 0.2f)
                {
                    petctrl_script.spawnedObject.transform.position = Vector3.MoveTowards(petctrl_script.spawnedObject.transform.position,
                                                                                          hitpoint,
                                                                                          0.01f);
                    Vector3 dir = hitpoint - petctrl_script.spawnedObject.transform.position;
                    dir.y = 0f;
                    Quaternion rot = Quaternion.LookRotation(dir.normalized);
                    petctrl_script.spawnedObject.transform.rotation = rot;
                    petctrl_script.spawnedObject.transform.GetChild(0).transform.rotation = rot;
                }
                else
                {
                    set_to_gravity();
                    track_flag = false;

                    //BoxCollider collider = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<BoxCollider>();
                    //Rigidbody rg_body = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Rigidbody>();
                    //collider.enabled = true;
                    //rg_body.isKinematic = false;

                    Vector3 dir = Camera.main.transform.position - petctrl_script.spawnedObject.transform.position;
                    dir.y = 0f;
                    Quaternion rot = Quaternion.LookRotation(dir.normalized);
                    petctrl_script.spawnedObject.transform.rotation = rot;
                    petctrl_script.spawnedObject.transform.GetChild(0).transform.rotation = rot;
                    Debug.Log("Idle animation excute___gameMode");
                    anim = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Animator>();
                    anim.Play("Idle");
                    //guide_image.sprite = guide_img_set[1];
                }

            }
        }

        public void start_scan()
        {
            if (!flag_scan_mode)
            {
                flag_scan_mode = true;
                flag_game_mode = false;
            }
            //list_points.Clear(); //
            //Meshing.meshPrefab = white_prefab;

            Arrow_L.SetActive(true);
            Arrow_R.SetActive(true);
            time_remaining = 15.0f;
            video_screen.SetActive(false);
            //scanning_panel.SetActive(true);
            shoot_bt.SetActive(false);
            time_text.enabled = true;
            //AudioSource audio = GameObject.Find("Audio player").GetComponent<AudioSource>();
            //audio.Play();

        }

        public void game_restartBt_no_click()
        {
            time_text.text = "";
            //ê²Œì„ ì„ íƒí•˜ëŠ” sceneìœ¼ë¡œ ë‹¤ì‹œ ì „í™˜
            SceneManagement.SceneManager.LoadScene("Chapter5");
        }

        public void start_game()
        {
            time_text.text = "";
            extract_points();
            Debug.Log("flag_game_mode: " + flag_game_mode);
            if (!flag_game_mode)
            {
                flag_game_mode = true;
                flag_scan_mode = false;
            }
            set_to_kinematic();//set to kinematic
            flag_game_started = true;
            pet_move_flag = true;
            //petctrl_script.game_start_msg.SetActive(false);
            start_game_bt.SetActive(false);
            start_game_bt_no.SetActive(false);

            //gamming_panel.SetActive(true);
            gamming_take_picture_bt.SetActive(false);
            gamming_shoot_bt.SetActive(false);
            //AudioSource audio = GameObject.Find("Audio player").GetComponent<AudioSource>();
            //if(audio.isPlaying) audio.Stop();

        }



        public void set_to_kinematic()
        {
            Rigidbody rg_body = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Rigidbody>();
            rg_body.isKinematic = true;
            rg_body.useGravity = false;
            Debug.Log("Kinematic mode");
        }

        public void set_to_gravity()
        {
            Rigidbody rg_body = petctrl_script.spawnedObject.transform.GetChild(0).GetComponent<Rigidbody>();
            rg_body.useGravity = true;
            rg_body.isKinematic = false;
            Debug.Log("Gravity mode");
        }


        public static int[] MakeRandomNumbers(int maxValue, int randomSeed = 0)
        {
            return MakeRandomNumbers(0, maxValue, randomSeed);
        }

        /// <summary>
        /// ???????? ???? ???? ???? ?????? ??????
        /// </summary>
        /// <param name="minValue">??????(????)</param>
        /// <param name="maxValue">??????(????)</param>
        /// <param name="count">???? ????</param>
        /// <param name="isDuplicate">???? ???? ????</param>
        /// <param name="randomSeed">???? ????</param>
        /// <returns></returns>
        public static int[] MakeRandomNumbers(int minValue, int maxValue, int randomSeed = 0)
        {
            if (randomSeed == 0)
                randomSeed = (int)System.DateTime.Now.Ticks;

            List<int> values = new List<int>();
            for (int v = minValue; v < maxValue; v++)
            {
                values.Add(v);
            }

            int[] result = new int[maxValue - minValue];
            System.Random random = new System.Random(Seed: randomSeed);
            int i = 0;
            while (values.Count > 0)
            {
                int randomValue = values[random.Next(0, values.Count)];
                result[i++] = randomValue;

                if (!values.Remove(randomValue))
                {
                    // Exception
                    break;
                }
            }

            return result;
        }
    }
}